In [2]:
import pandas as pd

In [3]:
df = pd.read_csv(r'cleaned_retail.csv')

In [4]:
df_clean = df.copy()

In [5]:
cancelled = df_clean[df_clean['Invoice'].astype(str).str.startswith('C')]

In [6]:
cancelled.shape

(18872, 9)

In [7]:
df_clean = df_clean[~df_clean['Invoice'].astype(str).str.startswith('C')]

In [8]:
# Removed cancelled invoices (Invoice starting with 'C') to ensure only successful transactions are analyzed

In [9]:
df_clean['Customer ID'].isnull().sum()

228114

In [10]:
df_clean = df_clean.dropna(subset=['Customer ID'])

# Removing negative quantities

In [11]:
df_clean[df_clean['Quantity'] < 0].shape

(0, 9)

In [12]:
df_clean = df_clean[df_clean['Quantity'] > 0]

In [13]:
# Removed transactions with negative quantities to ensure only valid purchases are analyzed.

# Converting InvoiceDate to Datetime

In [14]:
df_clean['InvoiceDate'] = pd.to_datetime(df_clean['InvoiceDate'])

In [15]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 767439 entries, 0 to 1014424
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      767439 non-null  object
 1   StockCode    767439 non-null  object
 2   Description  767439 non-null  object
 3   Quantity     767439 non-null  int64
 4   InvoiceDate  767439 non-null  datetime64[ns]
 5   Price        767439 non-null  float64
 6   Customer ID  767439 non-null  float64
 7   Country      767439 non-null  object
 8   Revenue      767439 non-null  float64
dtypes: datetime64[ns](1), float64(3), int64(1), object(4)
memory usage: 58.6+ MB

In [16]:
# creating revenue column
df_clean['Revenue'] = df_clean['Quantity'] * df_clean['Price']

In [17]:
# Before Cleaning
df.shape

(1014425, 9)

In [18]:
# After Cleaning
df_clean.shape

(767439, 9)

# Comparison Table

In [19]:
comparison = pd.DataFrame({
    "Stage": ["Before Cleaning", "After Cleaning"],
    "Rows": [df.shape[0], df_clean.shape[0]],
    "Columns": [df.shape[1], df_clean.shape[1]]
})

comparison

             Stage     Rows  Columns
0  Before Cleaning  1014425        9
1   After Cleaning   767439        9

In [21]:
#Percentage Data Removed
((df.shape[0] - df_clean.shape[0]) / df.shape[0]) * 100

24.34738891490253

# Cleaned Dataframe

In [22]:
df_clean.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Revenue
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,83.4
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,100.8
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,30.0

In [23]:
df_clean.to_csv("cleaned_online_retail.csv", index=False)