# Revenue Column

In [3]:
import pandas as pd

df_clean = pd.read_csv("cleaned_online_retail.csv")

In [7]:
# Reveue = Quantity X Price
df_clean['Revenue'] = df_clean['Quantity'] * df_clean['Price']

In [9]:
df_clean[['Quantity','Price','Revenue']].head()
# Created a Revenue feature by multiplying Quantity with UnitPrice to represent total transaction value.

   Quantity  Price  Revenue
0        12   6.95     83.4
1        12   6.75     81.0
2        12   6.75     81.0
3        48   2.10    100.8
4        24   1.25     30.0

# Extract Order Month

In [13]:
df_clean['InvoiceDate'] = pd.to_datetime(df_clean['InvoiceDate'])

In [14]:
df_clean['OrderMonth'] = df_clean['InvoiceDate'].dt.month

In [16]:
df_clean[['InvoiceDate','OrderMonth']].head()
# Extracted OrderMonth from InvoiceDate to analyze monthly sales trends.

          InvoiceDate  OrderMonth
0 2009-12-01 07:45:00          12
1 2009-12-01 07:45:00          12
2 2009-12-01 07:45:00          12
3 2009-12-01 07:45:00          12
4 2009-12-01 07:45:00          12